name = "JuliaDataAnalysis"
authors = ["Rob J Goedman"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
DataFrames = "1.3"
DocStringExtensions = "0.8.6"
DrWatson = "2.9.1"
julia = "1.9.0"
